# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ScaleTableView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScaleTableView

  target 'ScaleTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScaleTableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'AFNetworking', '~> 3.1.0'
 pod 'YYWebImage'
end
