# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'BuildTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BuildTest

  target 'BuildTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuildTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

 pod 'Masonry', '~> 1.0.2'

end
