# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'PlayGif' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlayGif

  target 'PlayGifTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlayGifUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SDWebImage', '~> 4.0.0-beta2'
   pod 'YYWebImage', '~> 1.0.5'
end
