platform:ios,'8.0'
target 'Music' do
 pod 'AFNetworking', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry', '~> 1.0.2'
   pod 'MJRefresh', '~> 3.1.12'
pod 'BlocksKit', '~> 2.2.5'
pod 'Mantle', '~> 2.0.7'
pod 'MJExtension', '~> 3.0.13'
pod 'SDWebImage', '~>3.8'
end
